### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [10]:
# 1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

import pandas as pd 

data1 = {
    "Name" : ["a","b","c"],
    "Age"  : [20,21,22]
}

df1 = pd.DataFrame(data1)

print(df1)


data2 = {
    "Name":["a","b","c"],
    "Gender": ["male","female","male"]
}

df2 = pd.DataFrame(data2)

print(df2)


## JOIN BOTH THE DFs BASED ON THE SAME COLUMN

Merged = pd.merge(
    df1,
    df2,
    on = "Name",
    how = "outer")

print(Merged)

  Name  Age
0    a   20
1    b   21
2    c   22
  Name  Gender
0    a    male
1    b  female
2    c    male
  Name  Age  Gender
0    a   20    male
1    b   21  female
2    c   22    male

In [ ]:
# 2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

import pandas as pd 

data1 = {
    "Name" : ["a","b","c"],
    "Age"  : [20,21,22]
}

df1 = pd.DataFrame(data1)

print(df1)


data2 = {
    "Name":["a","b","c"],
    "Gender": ["male","female","male"]
}

df2 = pd.DataFrame(data2)

print(df2)


## Concatenate the DataFrames along the rows and along the columns.

##Stacks one below each other

pd.concat([df1,df2],axis=0)


pd.concat([df1,df2],axis=1)

  Name  Age
0    a   20
1    b   21
2    c   22
  Name  Gender
0    a    male
1    b  female
2    c    male

  Name  Age Name  Gender
0    a   20    a    male
1    b   21    b  female
2    c   22    c    male

## Concat()

* concat does not cares about common columns like joins do 

* concat just stacks them

    * concat = stack

    * merge = match

In [17]:
# 2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

import pandas as pd 

data1 = {
    "Name" : ["a","b","c"],
    "Age"  : [20,21,22]
}

df1 = pd.DataFrame(data1)

print(df1)


data2 = {
    "Height":[160,165,162],
    "Gender": ["male","female","male"]
}

df2 = pd.DataFrame(data2)

print(df2)


## Concatenate the DataFrames along the rows and along the columns.

##Stacks one below each other

pd.concat([df1,df2],axis=0)


pd.concat([df1,df2],axis=1)

  Name  Age
0    a   20
1    b   21
2    c   22
   Height  Gender
0     160    male
1     165  female
2     162    male

  Name  Age  Height  Gender
0    a   20     160    male
1    b   21     165  female
2    c   22     162    male