# PANDAS - DATAFRAME & SERIES 

Pandas is a poweful data manipulation library in Python widely used for data cleaning and data analysis.
It provides two primary data structures 

* Series :  One dimensional array-like object 

* Data Frames : Two Dimensional , size-mutable, and potentially hetrogeneous tabular data structure with labelled axes (rows & columns).

In [4]:
#A Series
#It is a one dimensional array like object , that can hold onto any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from dictionary
data = {"a":1,"b":2,"c":3}     
# defualt index in dict was - 0 , 1, 2
# now my index becomes - a, b, c
series_Dict = pd.Series(data)
print(series_Dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ["a","b","c"]
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

# DATA FRAME

* A data frame in pandas is basically just like a table, just like an excel sheet
* It contains rows and columns
* It is mutable
* It is heterogeneous - can hold multiple data types

In [7]:
## Data Frame 
## How to create a data frame completely from basics
## from a dictionary of list


data = {
    "Name" : ["A","B","C"],
    "Age" : [25,30,45],
    "city" : ["Bangalore","New york","Delhi"]
}
## 3 columns , Many rows 

df = pd.DataFrame(data)
print(f"{df} \n {type(df)}")

  Name  Age       city
0    A   25  Bangalore
1    B   30   New york
2    C   45      Delhi
 <class 'pandas.core.frame.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['A', 25, 'Bangalore'],
       ['B', 30, 'New york'],
       ['C', 45, 'Delhi']], dtype=object)

In [25]:
## Create a Data frame from a list of dict

data1 = [
    {"Name" :"A", "Age":25, "City" : "Delhi"},
    {"Name" :"B", "Age":45, "City" : "Punjab"},
    {"Name" :"C", "Age":20, "City" : "Himachal"},
    {"Name" :"D", "Age":25, "City" : "Haryana"},
]
df = pd.DataFrame(data1)

print(f"{df}\n {type(df)}")

  Name  Age      City
0    A   25     Delhi
1    B   45    Punjab
2    C   20  Himachal
3    D   25   Haryana
 <class 'pandas.core.frame.DataFrame'>

In [16]:
df = pd.read_csv('data.csv')

print(df.head(5))

#print(df)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [17]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

# ACCESSING DATA FROM DATA FRAME

In [48]:
import pandas as pd 

data = {
    'Name' : ["Aksa","Rahul","Sara"],
    'Age' : [21,22,23]

}
df = pd.DataFrame(data)

#print(df)

## Now i will access data from here

# print(df["Name"])        # whole Name column
# print(df["Age"][1])
# print(type(df['Name']))   # one row = series


# loc = location-based in pandas 
# df.loc[row, column]

df.loc[0]
print(f"aksa {df.loc[0][0]}")
print(f"aksa {df.loc[0][1]}")

aksa Aksa
aksa 21

C:\Users\aksas\AppData\Local\Temp\ipykernel_24868\3909088898.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"aksa {df.loc[0][0]}")
C:\Users\aksas\AppData\Local\Temp\ipykernel_24868\3909088898.py:24: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"aksa {df.loc[0][1]}")

In [51]:
## Accessing a specified element

df

    Name  Age
0   Aksa   21
1  Rahul   22
2   Sara   23

In [54]:
df.at[1,'Name']

'Rahul'

In [58]:
#Accessing a specified element using isinstance

df

    Name  Age
0   Aksa   21
1  Rahul   22
2   Sara   23

In [61]:
df.iat[2,1]

23

In [ ]:
## Data manipulation with Data Frames

df

In [ ]:
## Adding a Column
df['Salary'] = [50000, 60000, 70000]

    Name  Age  Salary
0   Aksa   21   50000
1  Rahul   22   60000
2   Sara   23   70000

In [ ]:
df
## Remove a column
df.drop('Salary',axis=1,inplace=True)

    Name  Age
0   Aksa   21
1  Rahul   22
2   Sara   23

In [75]:
## ADD Age to Column

df['Age']+1

0    22
1    23
2    24
Name: Age, dtype: int64

In [78]:
df.drop(0,inplace=True)

In [79]:
df

    Name  Age
1  Rahul   22
2   Sara   23